//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Messages struct {
	ID        uuid.UUID `sql:"primary_key"`
	ChatID    uuid.UUID
	UserID    *uuid.UUID
	BotID     *uuid.UUID
	Content   string
	CreatedAt time.Time
}
