import { Footer } from "../../components/Footer";
import { SimpleNavBar } from "../../components/SimpleNavBar";
import { StarsBackground } from "../../components/StarsBackground";
import { TermSection } from "./components/TermSection";

export const TermsOfService = () => {
	return (
		<div className="scrollbar-thin scrollbar-thumb-ga-white-default scrollbar-track-ga-purple-darkest scrollbar flex min-h-screen flex-col justify-between gap-12 bg-ga-black-lighter">
			<StarsBackground />

			<div>
				<SimpleNavBar />
			</div>

			<div className="mx-auto flex max-w-5xl flex-col gap-12 px-4">
				<h2 className="text-3xl font-bold">
					Terms Of Service for{" "}
					<span className="whitespace-nowrap">
						Pygmalion<span className="text-ga-purple-default">AI</span>
					</span>
				</h2>

				<div className="flex flex-col gap-4">
					<h3 className="text-lg font-bold italic">
						Effective Date: [Insert Date]
					</h3>
					<p className="italic">
						Welcome to PygmalionAI, an open-source project dedicated to creating
						large language models for chat and role-play purposes. Before using
						our services, please read these Terms of Service carefully. By
						accessing or using PygmalionAI, you agree to be bound by these
						terms, so it is essential to review them periodically, as they are
						subject to change without notice. If you do not agree with these
						terms, you must refrain from using PygmalionAI.
					</p>
				</div>

				<div className="flex flex-col gap-4">
					<TermSection level={1} content="1. Acceptable Use">
						<TermSection
							level={2}
							content="1.1. PygmalionAI is intended for use solely for chat and role-play purposes. Users are not allowed to utilize the service for any illegal, malicious, or harmful activities that may infringe upon the rights of others."
						/>
						<TermSection
							level={2}
							content="1.2. You must be at least 18 years of age to use PygmalionAI, or if you are under 18, you must have parental or legal guardian consent to use our services."
						/>
					</TermSection>

					<TermSection level={1} content="2. Intellectual Property">
						<TermSection
							level={2}
							content="2.1. PygmalionAI retains all intellectual property rights related to the project, including but not limited to the software, documentation, and any associated materials."
						/>
						<TermSection
							level={2}
							content="2.2. Users are granted a limited, non-exclusive, non-transferable license to use PygmalionAI solely for personal, non-commercial purposes."
						/>
					</TermSection>

					<TermSection level={1} content="3. Code of Conduct">
						<TermSection
							level={2}
							content="3.1. Users are expected to engage respectfully and responsibly when using PygmalionAI, refraining from engaging in offensive, abusive, or harmful behavior towards others."
						/>
						<TermSection
							level={2}
							content="3.2. Any content generated using PygmalionAI should not violate any applicable laws, including copyright,
				trademark, or privacy rights of third parties."
						/>
						<TermSection
							level={2}
							content="3.3. Users are prohibited from using PygmalionAI to spread misinformation or engage in activities that could harm the reputation of the project."
						/>
					</TermSection>

					<TermSection level={1} content="4. Disclaimer of Warranty">
						<TermSection
							level={2}
							content='4.1. PygmalionAI is provided "as is" without warranties of any kind, whether express or implied.'
						/>
						<TermSection
							level={2}
							content="4.2. While we strive to maintain accuracy, PygmalionAI does not guarantee the correctness, reliability, or completeness of the information generated by the language model."
						/>
					</TermSection>

					<TermSection level={1} content="6. Limitation of Liability">
						<TermSection
							level={2}
							content="6.1. In no event shall PygmalionAI or its contributors be liable for any indirect, incidental, special, consequential, or punitive damages arising from the use of or inability to use the service."
						/>
						<TermSection
							level={2}
							content="6.2. PygmalionAI shall not be held responsible for any content generated by the users or any third-party content accessed through the service."
						/>
					</TermSection>

					<TermSection level={1} content="7. Indemnification">
						<TermSection
							level={2}
							content="7.1. Users agree to indemnify and hold harmless PygmalionAI and its contributors from any claims, damages, losses, or liabilities arising from their use of the service or any violation of these Terms of Service."
						/>
					</TermSection>

					<TermSection level={1} content="8. Suspension and Termination">
						<TermSection
							level={2}
							content="8.1. PygmalionAI reserves the right to suspend or terminate access to the service at any time, with or without cause and without prior notice."
						/>
						<TermSection
							level={2}
							content="8.2. Upon termination, all provisions of these Terms of Service which by their nature should survive, including but not limited to intellectual property rights, warranty disclaimers, and limitations of liability, shall remain in effect."
						/>
					</TermSection>

					<TermSection level={1} content="9. Governing Law">
						<TermSection
							level={2}
							content="9.1. These Terms of Service shall be governed by and construed in accordance with the laws of [Jurisdiction], without regard to its conflicts of law principles."
						/>
					</TermSection>
				</div>

				<div className="flex max-w-2xl flex-col gap-4">
					<p className="text-ga-purple-lightest">
						By using PygmalionAI, you acknowledge that you have read,
						understood, and agree to be bound by these Terms of Service. If you
						have any questions or concerns, please contact us at [Contact
						Email].
					</p>
				</div>
			</div>

			<Footer />
		</div>
	);
};
