// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: galatea/v1/chat.proto

package galateav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SenderType int32

const (
	SenderType_SENDER_TYPE_UNSPECIFIED SenderType = 0
	SenderType_SENDER_TYPE_USER        SenderType = 1
	SenderType_SENDER_TYPE_BOT         SenderType = 2
)

// Enum value maps for SenderType.
var (
	SenderType_name = map[int32]string{
		0: "SENDER_TYPE_UNSPECIFIED",
		1: "SENDER_TYPE_USER",
		2: "SENDER_TYPE_BOT",
	}
	SenderType_value = map[string]int32{
		"SENDER_TYPE_UNSPECIFIED": 0,
		"SENDER_TYPE_USER":        1,
		"SENDER_TYPE_BOT":         2,
	}
)

func (x SenderType) Enum() *SenderType {
	p := new(SenderType)
	*p = x
	return p
}

func (x SenderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SenderType) Descriptor() protoreflect.EnumDescriptor {
	return file_galatea_v1_chat_proto_enumTypes[0].Descriptor()
}

func (SenderType) Type() protoreflect.EnumType {
	return &file_galatea_v1_chat_proto_enumTypes[0]
}

func (x SenderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SenderType.Descriptor instead.
func (SenderType) EnumDescriptor() ([]byte, []int) {
	return file_galatea_v1_chat_proto_rawDescGZIP(), []int{0}
}

type ChatMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Sender    SenderType `protobuf:"varint,2,opt,name=sender,proto3,enum=galatea.v1.SenderType" json:"sender,omitempty"`
	Message   string     `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	CreatedAt int64      `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_galatea_v1_chat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_galatea_v1_chat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_galatea_v1_chat_proto_rawDescGZIP(), []int{0}
}

func (x *ChatMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChatMessage) GetSender() SenderType {
	if x != nil {
		return x.Sender
	}
	return SenderType_SENDER_TYPE_UNSPECIFIED
}

func (x *ChatMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChatMessage) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type Chat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId   string         `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BotId    string         `protobuf:"bytes,3,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	Messages []*ChatMessage `protobuf:"bytes,4,rep,name=messages,proto3" json:"messages,omitempty"`
}

func (x *Chat) Reset() {
	*x = Chat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_galatea_v1_chat_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Chat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chat) ProtoMessage() {}

func (x *Chat) ProtoReflect() protoreflect.Message {
	mi := &file_galatea_v1_chat_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chat.ProtoReflect.Descriptor instead.
func (*Chat) Descriptor() ([]byte, []int) {
	return file_galatea_v1_chat_proto_rawDescGZIP(), []int{1}
}

func (x *Chat) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Chat) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Chat) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

func (x *Chat) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

type ChatAllRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ChatAllRequest) Reset() {
	*x = ChatAllRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_galatea_v1_chat_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatAllRequest) ProtoMessage() {}

func (x *ChatAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_galatea_v1_chat_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatAllRequest.ProtoReflect.Descriptor instead.
func (*ChatAllRequest) Descriptor() ([]byte, []int) {
	return file_galatea_v1_chat_proto_rawDescGZIP(), []int{2}
}

type ChatAllResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chats []*Chat `protobuf:"bytes,1,rep,name=chats,proto3" json:"chats,omitempty"`
}

func (x *ChatAllResponse) Reset() {
	*x = ChatAllResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_galatea_v1_chat_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatAllResponse) ProtoMessage() {}

func (x *ChatAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_galatea_v1_chat_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatAllResponse.ProtoReflect.Descriptor instead.
func (*ChatAllResponse) Descriptor() ([]byte, []int) {
	return file_galatea_v1_chat_proto_rawDescGZIP(), []int{3}
}

func (x *ChatAllResponse) GetChats() []*Chat {
	if x != nil {
		return x.Chats
	}
	return nil
}

type ChatGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ChatGetRequest) Reset() {
	*x = ChatGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_galatea_v1_chat_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatGetRequest) ProtoMessage() {}

func (x *ChatGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_galatea_v1_chat_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatGetRequest.ProtoReflect.Descriptor instead.
func (*ChatGetRequest) Descriptor() ([]byte, []int) {
	return file_galatea_v1_chat_proto_rawDescGZIP(), []int{4}
}

func (x *ChatGetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ChatGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chat *Chat `protobuf:"bytes,1,opt,name=chat,proto3" json:"chat,omitempty"`
}

func (x *ChatGetResponse) Reset() {
	*x = ChatGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_galatea_v1_chat_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatGetResponse) ProtoMessage() {}

func (x *ChatGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_galatea_v1_chat_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatGetResponse.ProtoReflect.Descriptor instead.
func (*ChatGetResponse) Descriptor() ([]byte, []int) {
	return file_galatea_v1_chat_proto_rawDescGZIP(), []int{5}
}

func (x *ChatGetResponse) GetChat() *Chat {
	if x != nil {
		return x.Chat
	}
	return nil
}

type ChatCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BotId string `protobuf:"bytes,1,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
}

func (x *ChatCreateRequest) Reset() {
	*x = ChatCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_galatea_v1_chat_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCreateRequest) ProtoMessage() {}

func (x *ChatCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_galatea_v1_chat_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCreateRequest.ProtoReflect.Descriptor instead.
func (*ChatCreateRequest) Descriptor() ([]byte, []int) {
	return file_galatea_v1_chat_proto_rawDescGZIP(), []int{6}
}

func (x *ChatCreateRequest) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

type ChatCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chat *Chat `protobuf:"bytes,1,opt,name=chat,proto3" json:"chat,omitempty"`
}

func (x *ChatCreateResponse) Reset() {
	*x = ChatCreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_galatea_v1_chat_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCreateResponse) ProtoMessage() {}

func (x *ChatCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_galatea_v1_chat_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCreateResponse.ProtoReflect.Descriptor instead.
func (*ChatCreateResponse) Descriptor() ([]byte, []int) {
	return file_galatea_v1_chat_proto_rawDescGZIP(), []int{7}
}

func (x *ChatCreateResponse) GetChat() *Chat {
	if x != nil {
		return x.Chat
	}
	return nil
}

type ChatDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ChatDeleteRequest) Reset() {
	*x = ChatDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_galatea_v1_chat_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatDeleteRequest) ProtoMessage() {}

func (x *ChatDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_galatea_v1_chat_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatDeleteRequest.ProtoReflect.Descriptor instead.
func (*ChatDeleteRequest) Descriptor() ([]byte, []int) {
	return file_galatea_v1_chat_proto_rawDescGZIP(), []int{8}
}

func (x *ChatDeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ChatDeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chat *Chat `protobuf:"bytes,1,opt,name=chat,proto3" json:"chat,omitempty"`
}

func (x *ChatDeleteResponse) Reset() {
	*x = ChatDeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_galatea_v1_chat_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatDeleteResponse) ProtoMessage() {}

func (x *ChatDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_galatea_v1_chat_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatDeleteResponse.ProtoReflect.Descriptor instead.
func (*ChatDeleteResponse) Descriptor() ([]byte, []int) {
	return file_galatea_v1_chat_proto_rawDescGZIP(), []int{9}
}

func (x *ChatDeleteResponse) GetChat() *Chat {
	if x != nil {
		return x.Chat
	}
	return nil
}

type ChatSubscribeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ChatSubscribeRequest) Reset() {
	*x = ChatSubscribeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_galatea_v1_chat_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatSubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatSubscribeRequest) ProtoMessage() {}

func (x *ChatSubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_galatea_v1_chat_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatSubscribeRequest.ProtoReflect.Descriptor instead.
func (*ChatSubscribeRequest) Descriptor() ([]byte, []int) {
	return file_galatea_v1_chat_proto_rawDescGZIP(), []int{10}
}

func (x *ChatSubscribeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ChatSubscribeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Sender  SenderType `protobuf:"varint,2,opt,name=sender,proto3,enum=galatea.v1.SenderType" json:"sender,omitempty"`
	Message string     `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ChatSubscribeResponse) Reset() {
	*x = ChatSubscribeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_galatea_v1_chat_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatSubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatSubscribeResponse) ProtoMessage() {}

func (x *ChatSubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_galatea_v1_chat_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatSubscribeResponse.ProtoReflect.Descriptor instead.
func (*ChatSubscribeResponse) Descriptor() ([]byte, []int) {
	return file_galatea_v1_chat_proto_rawDescGZIP(), []int{11}
}

func (x *ChatSubscribeResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChatSubscribeResponse) GetSender() SenderType {
	if x != nil {
		return x.Sender
	}
	return SenderType_SENDER_TYPE_UNSPECIFIED
}

func (x *ChatSubscribeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ChatSendMessageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChatId  string `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ChatSendMessageRequest) Reset() {
	*x = ChatSendMessageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_galatea_v1_chat_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatSendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatSendMessageRequest) ProtoMessage() {}

func (x *ChatSendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_galatea_v1_chat_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatSendMessageRequest.ProtoReflect.Descriptor instead.
func (*ChatSendMessageRequest) Descriptor() ([]byte, []int) {
	return file_galatea_v1_chat_proto_rawDescGZIP(), []int{12}
}

func (x *ChatSendMessageRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *ChatSendMessageRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ChatSendMessageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message *ChatMessage `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ChatSendMessageResponse) Reset() {
	*x = ChatSendMessageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_galatea_v1_chat_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatSendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatSendMessageResponse) ProtoMessage() {}

func (x *ChatSendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_galatea_v1_chat_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatSendMessageResponse.ProtoReflect.Descriptor instead.
func (*ChatSendMessageResponse) Descriptor() ([]byte, []int) {
	return file_galatea_v1_chat_proto_rawDescGZIP(), []int{13}
}

func (x *ChatSendMessageResponse) GetMessage() *ChatMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

var File_galatea_v1_chat_proto protoreflect.FileDescriptor

var file_galatea_v1_chat_proto_rawDesc = []byte{
	0x0a, 0x15, 0x67, 0x61, 0x6c, 0x61, 0x74, 0x65, 0x61, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x68, 0x61,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x67, 0x61, 0x6c, 0x61, 0x74, 0x65, 0x61,
	0x2e, 0x76, 0x31, 0x22, 0x86, 0x01, 0x0a, 0x0b, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x2e, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x67, 0x61, 0x6c, 0x61, 0x74, 0x65, 0x61, 0x2e, 0x76, 0x31,
	0x2e, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x52, 0x06, 0x73, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1d, 0x0a,
	0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x7b, 0x0a, 0x04,
	0x43, 0x68, 0x61, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x15, 0x0a,
	0x06, 0x62, 0x6f, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62,
	0x6f, 0x74, 0x49, 0x64, 0x12, 0x33, 0x0a, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x61, 0x6c, 0x61, 0x74, 0x65, 0x61,
	0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52,
	0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x22, 0x10, 0x0a, 0x0e, 0x43, 0x68, 0x61,
	0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x39, 0x0a, 0x0f, 0x43,
	0x68, 0x61, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26,
	0x0a, 0x05, 0x63, 0x68, 0x61, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x67, 0x61, 0x6c, 0x61, 0x74, 0x65, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x52,
	0x05, 0x63, 0x68, 0x61, 0x74, 0x73, 0x22, 0x20, 0x0a, 0x0e, 0x43, 0x68, 0x61, 0x74, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x37, 0x0a, 0x0f, 0x43, 0x68, 0x61, 0x74,
	0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x04, 0x63,
	0x68, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x67, 0x61, 0x6c, 0x61,
	0x74, 0x65, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x52, 0x04, 0x63, 0x68, 0x61,
	0x74, 0x22, 0x2a, 0x0a, 0x11, 0x43, 0x68, 0x61, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x62, 0x6f, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x6f, 0x74, 0x49, 0x64, 0x22, 0x3a, 0x0a,
	0x12, 0x43, 0x68, 0x61, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x04, 0x63, 0x68, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x67, 0x61, 0x6c, 0x61, 0x74, 0x65, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x43,
	0x68, 0x61, 0x74, 0x52, 0x04, 0x63, 0x68, 0x61, 0x74, 0x22, 0x23, 0x0a, 0x11, 0x43, 0x68, 0x61,
	0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x3a,
	0x0a, 0x12, 0x43, 0x68, 0x61, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x04, 0x63, 0x68, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x67, 0x61, 0x6c, 0x61, 0x74, 0x65, 0x61, 0x2e, 0x76, 0x31, 0x2e,
	0x43, 0x68, 0x61, 0x74, 0x52, 0x04, 0x63, 0x68, 0x61, 0x74, 0x22, 0x26, 0x0a, 0x14, 0x43, 0x68,
	0x61, 0x74, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x71, 0x0a, 0x15, 0x43, 0x68, 0x61, 0x74, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72,
	0x69, 0x62, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2e, 0x0a, 0x06, 0x73,
	0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x67, 0x61,
	0x6c, 0x61, 0x74, 0x65, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x4b, 0x0a, 0x16, 0x43, 0x68, 0x61, 0x74, 0x53, 0x65, 0x6e,
	0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x17, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x63, 0x68, 0x61, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x22, 0x4c, 0x0a, 0x17, 0x43, 0x68, 0x61, 0x74, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17,
	0x2e, 0x67, 0x61, 0x6c, 0x61, 0x74, 0x65, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68, 0x61, 0x74,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2a, 0x54, 0x0a, 0x0a, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1b,
	0x0a, 0x17, 0x53, 0x45, 0x4e, 0x44, 0x45, 0x52, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e,
	0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x53,
	0x45, 0x4e, 0x44, 0x45, 0x52, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x53, 0x45, 0x52, 0x10,
	0x01, 0x12, 0x13, 0x0a, 0x0f, 0x53, 0x45, 0x4e, 0x44, 0x45, 0x52, 0x5f, 0x54, 0x59, 0x50, 0x45,
	0x5f, 0x42, 0x4f, 0x54, 0x10, 0x02, 0x32, 0xe3, 0x03, 0x0a, 0x0b, 0x43, 0x68, 0x61, 0x74, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x42, 0x0a, 0x07, 0x43, 0x68, 0x61, 0x74, 0x41, 0x6c,
	0x6c, 0x12, 0x1a, 0x2e, 0x67, 0x61, 0x6c, 0x61, 0x74, 0x65, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x43,
	0x68, 0x61, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e,
	0x67, 0x61, 0x6c, 0x61, 0x74, 0x65, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x41,
	0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x42, 0x0a, 0x07, 0x43, 0x68,
	0x61, 0x74, 0x47, 0x65, 0x74, 0x12, 0x1a, 0x2e, 0x67, 0x61, 0x6c, 0x61, 0x74, 0x65, 0x61, 0x2e,
	0x76, 0x31, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1b, 0x2e, 0x67, 0x61, 0x6c, 0x61, 0x74, 0x65, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x43,
	0x68, 0x61, 0x74, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4b,
	0x0a, 0x0a, 0x43, 0x68, 0x61, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x1d, 0x2e, 0x67,
	0x61, 0x6c, 0x61, 0x74, 0x65, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x67, 0x61,
	0x6c, 0x61, 0x74, 0x65, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4b, 0x0a, 0x0a, 0x43,
	0x68, 0x61, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x1d, 0x2e, 0x67, 0x61, 0x6c, 0x61,
	0x74, 0x65, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x67, 0x61, 0x6c, 0x61, 0x74,
	0x65, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5a, 0x0a, 0x0f, 0x43, 0x68, 0x61, 0x74,
	0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x22, 0x2e, 0x67, 0x61,
	0x6c, 0x61, 0x74, 0x65, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x53, 0x65, 0x6e,
	0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x23, 0x2e, 0x67, 0x61, 0x6c, 0x61, 0x74, 0x65, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68, 0x61,
	0x74, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x56, 0x0a, 0x0d, 0x43, 0x68, 0x61, 0x74, 0x53, 0x75, 0x62, 0x73,
	0x63, 0x72, 0x69, 0x62, 0x65, 0x12, 0x20, 0x2e, 0x67, 0x61, 0x6c, 0x61, 0x74, 0x65, 0x61, 0x2e,
	0x76, 0x31, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x67, 0x61, 0x6c, 0x61, 0x74, 0x65,
	0x61, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69,
	0x62, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x42, 0x23, 0x5a, 0x21,
	0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2f, 0x67, 0x6f, 0x2f, 0x70, 0x62, 0x2f, 0x67, 0x61, 0x6c,
	0x61, 0x74, 0x65, 0x61, 0x2f, 0x76, 0x31, 0x3b, 0x67, 0x61, 0x6c, 0x61, 0x74, 0x65, 0x61, 0x76,
	0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_galatea_v1_chat_proto_rawDescOnce sync.Once
	file_galatea_v1_chat_proto_rawDescData = file_galatea_v1_chat_proto_rawDesc
)

func file_galatea_v1_chat_proto_rawDescGZIP() []byte {
	file_galatea_v1_chat_proto_rawDescOnce.Do(func() {
		file_galatea_v1_chat_proto_rawDescData = protoimpl.X.CompressGZIP(file_galatea_v1_chat_proto_rawDescData)
	})
	return file_galatea_v1_chat_proto_rawDescData
}

var file_galatea_v1_chat_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_galatea_v1_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_galatea_v1_chat_proto_goTypes = []interface{}{
	(SenderType)(0),                 // 0: galatea.v1.SenderType
	(*ChatMessage)(nil),             // 1: galatea.v1.ChatMessage
	(*Chat)(nil),                    // 2: galatea.v1.Chat
	(*ChatAllRequest)(nil),          // 3: galatea.v1.ChatAllRequest
	(*ChatAllResponse)(nil),         // 4: galatea.v1.ChatAllResponse
	(*ChatGetRequest)(nil),          // 5: galatea.v1.ChatGetRequest
	(*ChatGetResponse)(nil),         // 6: galatea.v1.ChatGetResponse
	(*ChatCreateRequest)(nil),       // 7: galatea.v1.ChatCreateRequest
	(*ChatCreateResponse)(nil),      // 8: galatea.v1.ChatCreateResponse
	(*ChatDeleteRequest)(nil),       // 9: galatea.v1.ChatDeleteRequest
	(*ChatDeleteResponse)(nil),      // 10: galatea.v1.ChatDeleteResponse
	(*ChatSubscribeRequest)(nil),    // 11: galatea.v1.ChatSubscribeRequest
	(*ChatSubscribeResponse)(nil),   // 12: galatea.v1.ChatSubscribeResponse
	(*ChatSendMessageRequest)(nil),  // 13: galatea.v1.ChatSendMessageRequest
	(*ChatSendMessageResponse)(nil), // 14: galatea.v1.ChatSendMessageResponse
}
var file_galatea_v1_chat_proto_depIdxs = []int32{
	0,  // 0: galatea.v1.ChatMessage.sender:type_name -> galatea.v1.SenderType
	1,  // 1: galatea.v1.Chat.messages:type_name -> galatea.v1.ChatMessage
	2,  // 2: galatea.v1.ChatAllResponse.chats:type_name -> galatea.v1.Chat
	2,  // 3: galatea.v1.ChatGetResponse.chat:type_name -> galatea.v1.Chat
	2,  // 4: galatea.v1.ChatCreateResponse.chat:type_name -> galatea.v1.Chat
	2,  // 5: galatea.v1.ChatDeleteResponse.chat:type_name -> galatea.v1.Chat
	0,  // 6: galatea.v1.ChatSubscribeResponse.sender:type_name -> galatea.v1.SenderType
	1,  // 7: galatea.v1.ChatSendMessageResponse.message:type_name -> galatea.v1.ChatMessage
	3,  // 8: galatea.v1.ChatService.ChatAll:input_type -> galatea.v1.ChatAllRequest
	5,  // 9: galatea.v1.ChatService.ChatGet:input_type -> galatea.v1.ChatGetRequest
	7,  // 10: galatea.v1.ChatService.ChatCreate:input_type -> galatea.v1.ChatCreateRequest
	9,  // 11: galatea.v1.ChatService.ChatDelete:input_type -> galatea.v1.ChatDeleteRequest
	13, // 12: galatea.v1.ChatService.ChatSendMessage:input_type -> galatea.v1.ChatSendMessageRequest
	11, // 13: galatea.v1.ChatService.ChatSubscribe:input_type -> galatea.v1.ChatSubscribeRequest
	4,  // 14: galatea.v1.ChatService.ChatAll:output_type -> galatea.v1.ChatAllResponse
	6,  // 15: galatea.v1.ChatService.ChatGet:output_type -> galatea.v1.ChatGetResponse
	8,  // 16: galatea.v1.ChatService.ChatCreate:output_type -> galatea.v1.ChatCreateResponse
	10, // 17: galatea.v1.ChatService.ChatDelete:output_type -> galatea.v1.ChatDeleteResponse
	14, // 18: galatea.v1.ChatService.ChatSendMessage:output_type -> galatea.v1.ChatSendMessageResponse
	12, // 19: galatea.v1.ChatService.ChatSubscribe:output_type -> galatea.v1.ChatSubscribeResponse
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_galatea_v1_chat_proto_init() }
func file_galatea_v1_chat_proto_init() {
	if File_galatea_v1_chat_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_galatea_v1_chat_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_galatea_v1_chat_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Chat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_galatea_v1_chat_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatAllRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_galatea_v1_chat_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatAllResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_galatea_v1_chat_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_galatea_v1_chat_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_galatea_v1_chat_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_galatea_v1_chat_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatCreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_galatea_v1_chat_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_galatea_v1_chat_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatDeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_galatea_v1_chat_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatSubscribeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_galatea_v1_chat_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatSubscribeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_galatea_v1_chat_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatSendMessageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_galatea_v1_chat_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatSendMessageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_galatea_v1_chat_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_galatea_v1_chat_proto_goTypes,
		DependencyIndexes: file_galatea_v1_chat_proto_depIdxs,
		EnumInfos:         file_galatea_v1_chat_proto_enumTypes,
		MessageInfos:      file_galatea_v1_chat_proto_msgTypes,
	}.Build()
	File_galatea_v1_chat_proto = out.File
	file_galatea_v1_chat_proto_rawDesc = nil
	file_galatea_v1_chat_proto_goTypes = nil
	file_galatea_v1_chat_proto_depIdxs = nil
}
