// @generated by protoc-gen-connect-web v0.7.0 with parameter "target=ts"
// @generated from file galatea/v1/auth.proto (package galatea.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CheckRequest, CheckResponse, SignInRequest, SignInResponse, SignUpRequest, SignUpResponse, VerifyRequest, VerifyResponse } from "./auth_pb.js";
import { MethodIdempotency, MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service galatea.v1.AuthService
 */
export const AuthService = {
  typeName: "galatea.v1.AuthService",
  methods: {
    /**
     * @generated from rpc galatea.v1.AuthService.SignIn
     */
    signIn: {
      name: "SignIn",
      I: SignInRequest,
      O: SignInResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc galatea.v1.AuthService.SignUp
     */
    signUp: {
      name: "SignUp",
      I: SignUpRequest,
      O: SignUpResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc galatea.v1.AuthService.Verify
     */
    verify: {
      name: "Verify",
      I: VerifyRequest,
      O: VerifyResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc galatea.v1.AuthService.Check
     */
    check: {
      name: "Check",
      I: CheckRequest,
      O: CheckResponse,
      kind: MethodKind.Unary,
    idempotency: MethodIdempotency.NoSideEffects,
    },
  }
} as const;

