// @generated by protoc-gen-connect-web v0.7.0 with parameter "target=ts"
// @generated from file galatea/v1/chat.proto (package galatea.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ChatAllRequest, ChatAllResponse, ChatCreateRequest, ChatCreateResponse, ChatDeleteRequest, ChatDeleteResponse, ChatGetRequest, ChatGetResponse, ChatSendMessageRequest, ChatSendMessageResponse, ChatSubscribeRequest, ChatSubscribeResponse } from "./chat_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service galatea.v1.ChatService
 */
export const ChatService = {
  typeName: "galatea.v1.ChatService",
  methods: {
    /**
     * @generated from rpc galatea.v1.ChatService.ChatAll
     */
    chatAll: {
      name: "ChatAll",
      I: ChatAllRequest,
      O: ChatAllResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc galatea.v1.ChatService.ChatGet
     */
    chatGet: {
      name: "ChatGet",
      I: ChatGetRequest,
      O: ChatGetResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc galatea.v1.ChatService.ChatCreate
     */
    chatCreate: {
      name: "ChatCreate",
      I: ChatCreateRequest,
      O: ChatCreateResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc galatea.v1.ChatService.ChatDelete
     */
    chatDelete: {
      name: "ChatDelete",
      I: ChatDeleteRequest,
      O: ChatDeleteResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc galatea.v1.ChatService.ChatSendMessage
     */
    chatSendMessage: {
      name: "ChatSendMessage",
      I: ChatSendMessageRequest,
      O: ChatSendMessageResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc galatea.v1.ChatService.ChatSubscribe
     */
    chatSubscribe: {
      name: "ChatSubscribe",
      I: ChatSubscribeRequest,
      O: ChatSubscribeResponse,
      kind: MethodKind.ServerStreaming,
    },
  }
} as const;

